apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cvvyy2ylz-python
  janus-idp.io/tekton: cvvyy2ylz-python
  backstage.io/kubernetes-id: cvvyy2ylz-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cvvyy2ylz-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
