apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cvvyy2ylz-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cvvyy2ylz-python 
  name: cvvyy2ylz-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cvvyy2ylz-python 
